name: iwp

channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit
  - dask
  - jupyter
  - netcdf4
  - numpy
  - python
  - python-pptx
  - pytorch
  - torchvision
  - xarray
