name: iwp

channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=11.1.74
  - dask
  - netcdf4
  - numpy
  - python=3.8
  - python-pptx
  - pytorch=1.8.1=py3.8_cuda11.1_cudnn8.0.5_0
  - torchvision
  - xarray
